# Generated by Django 5.0.4 on 2024-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='epin',
            field=models.IntegerField(default=True),
        ),
    ]
