# Generated by Django 5.0.4 on 2024-05-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
