# Generated by Django 5.0.4 on 2024-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone_number',
            field=models.IntegerField(),
        ),
    ]
