# Generated by Django 5.0.3 on 2024-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=10)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
